name       : perl-test-regexp
version    : 2017040101
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/A/AB/ABIGAIL/Test-Regexp-2017040101.tar.gz : 35cb41df5c5017835b89b853d5a44e25e6da973b450e1edca51bba70e7041e54
license    : MIT
component  : programming.perl
summary    : Test::Regexp - Test your regular expressions
description: |
    Test::Regexp, a module to test regular expressions with.
builddeps  :
    - perl-test-pod
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
